version: "3.8"
services:
  db:
    image: amd64/mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    secrets:
     - mysql-root-password
     - db-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
  wordpress:
    depends_on:
     - db
    image: amd64/wordpress:6
    ports:
     - "8000:80"
    restart: always
    secrets:
     - db-password
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db-password
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
secrets:
  mysql-root-password:
    external: true
  db-password:
    external: true